# 深度学习
英文版深度学习：http://www.deeplearningbook.org/
中文翻译版深度学习：https://github.com/exacity/deeplearningbook-chinese

## 第1部分 应用数学与机器学习基础
## 第2章 线性代数
$$x= \begin{bmatrix}x_1 \\ x_2 \\ . \\ . \\ . \\ x_n\end{bmatrix}$$

In [5]:
import numpy as np
M = np.arange(9).reshape(3, 3)
C = np.arange(3).reshape(1, 3)
print("M:")
print(M)
print("C:")
print(C)
print("M+C:")
print(M+C)

M:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
C:
[[0 1 2]]
M+C:
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]
